# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='achieved_count_per_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='minimum_target_per_hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reason',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
