# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171012_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='time',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
