# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userbrand_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrand',
            name='mobile_number',
            field=models.CharField(default='9965615321', max_length=10),
            preserve_default=False,
        ),
    ]
