# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 04:33
from __future__ import unicode_literals

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171026_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrand',
            name='image_url',
            field=models.ImageField(blank=True, default='profile/profile-default.png', max_length=200, null=True, upload_to=app.utils.update_filename),
        ),
    ]
