# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-27 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171027_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='type',
        ),
    ]
