# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_businessunit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrand',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
