# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171028_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbrand',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
