# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 07:05
from __future__ import unicode_literals

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='profile/gm.png', max_length=200, null=True, upload_to=app.utils.update_logo),
        ),
    ]
