# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171205_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='product',
        ),
        migrations.AddField(
            model_name='planning',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
    ]
