# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180116_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='product',
        ),
        migrations.AddField(
            model_name='planning',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
            preserve_default=False,
        ),
    ]
